Minor fix in how config files are found
If app is None, Python won't be happy:

    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'